# Generated by Django 4.2.30 on 2026-05-17 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, help_text='Why was this recommended?', max_length=255)),
                ('score', models.FloatField(default=0.0, help_text='Similarity or recommendation score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='aircraft.aircraft')),
                ('recommended_aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for', to='aircraft.aircraft')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('aircraft', 'recommended_aircraft')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='aircraft.aircraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'aircraft')},
            },
        ),
    ]
