# Generated by Django 4.2.30 on 2026-05-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('first_flight', models.DateField(blank=True, null=True)),
                ('speed', models.CharField(blank=True, help_text='Top speed, e.g., Mach 2.0 or 1,500 mph', max_length=100)),
                ('range', models.CharField(blank=True, help_text='Operational range, e.g., 2,000 miles', max_length=100)),
                ('crew', models.IntegerField(default=1)),
                ('role', models.CharField(max_length=100)),
                ('weapons', models.TextField(blank=True)),
                ('engine_type', models.CharField(blank=True, max_length=100)),
                ('generation', models.CharField(blank=True, max_length=50)),
                ('war_usage', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='aircraft_images/')),
                ('model_file', models.FileField(blank=True, help_text='3D model file (e.g. .gltf, .obj)', null=True, upload_to='aircraft_models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eras', models.ManyToManyField(blank=True, related_name='aircraft', to='aircraft.era')),
            ],
            options={
                'verbose_name_plural': 'Aircraft',
                'ordering': ['name'],
            },
        ),
    ]
