# Generated by Django 6.0.5 on 2026-05-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='aircraft/'),
        ),
    ]
